# .woodpecker.yml
clone:
  git:
    image: woodpeckerci/plugin-git
    settings:
      partial: false
      depth: 5
pipeline:
  build:
    image: debian
    commands:
      - echo "This is the build step"
  a-test-step:
    image: debian
    commands:
      - echo "Testing..."
