skip_clone: true
pipeline:
  steps:
  - name: build-image
    image: docker
    commands:
      - docker build --rm -t local/woodpecker-test .
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  - name: build-project
    image: local/project-image
    commands:
      - ./build.sh
