# skip_clone: true
clone:
  git:
    image: woodpeckerci/plugin-git
pipeline:
 test:
    image: alpine
    commands:
      - echo "Woodpecker CI is working!"
 build:
    image: docker:19.03.12
    commands:
      - docker build -t test:latest .

